### ISSUE TITLE
better to remove the install.bat file as it is auto in comfyUI

### ISSUE THREAD

**Issue by jags111** [gokayfem/ComfyUI_VLM_nodes#1]
Hai.. it is better to skip the install bat file as it is easy to install same in comfy and it may interfere with other installs. can you suppress same as Comfy Manager will handle most of it.

Secondly can you specify the model paths and loading of the LLM models as it is not clear in this repo. how do we ensure if other LLM models needs to be tested using your nodes.
third using openAPI is not possible as they changed all the connecting info

**Comment by gokayfem** [comment]
i fixed the openai code and also deleted the installer.bat
im currently training some llms for auto-prompting, i will add the choosing llm feature soon.

**Comment by jags111** [comment]
awesome and thanks. If you could add some more models to work with your nodes it will be a game changer. Especially with Image 2 txt there is not much comfy nodes available. Also if you can have a look at the stable LLM portfolio and add them to work for both text and image to text guidance it will have a major impact. Do let me know if any of same can be done. thanks a lot.

**Comment by jags111** [comment]
also kindly see if you can find a way to add (https://github.com/THUDM/CogVLM) and other VLM models as these are some open source ones with no issues on commercial use cases. Also have a look into (https://github.com/SkunkworksAI/BakLLaVA)  (https://github.com/DLYuanGod/TinyGPT-V) and many VLM models that will be super cool.

**Comment by gokayfem** [comment]
added bakllava and other llava models, now i will work on other ones

**Comment by jags111** [comment]
superb and awesome
