### ISSUE TITLE
Please create LLM Sampler Unload Memory Node

### ISSUE THREAD

**Issue by wardensc2** [gokayfem/ComfyUI_VLM_nodes#115]
Hi @gokayfem 

I already use your Node for months, however since the LLM Sampler Node without image input does not have unload memory function so my automatic workflow is cut short due to out of Vram. Please create the same function as unload memory like your LLava Node

Thank you so much for your effort

**Comment by gokayfem** [comment]
done

**Comment by wardensc2** [comment]
Thank you so much

**Comment by wardensc2** [comment]
> done

Hi @gokayfem 

Thank you so much for your effort. I wonder can I ask a little more from Unload Memory Node.

Since I use multi LLM samplers link together. With the new unload node which include loading LLM checkpoint. My workflow need to unload then load then unload then load which consume more time. I just want to keep the model when running multi LLM sampler and unload memory in the last node LLM sampler only. Can you separate loading LLM checkpoint so I can use your node LLM loader and only set up unload node in the last LLM sampler node

**Comment by gokayfem** [comment]
that is really hard inside comfyui because of it's graph structure. it is based on litegraph it does not work like that.

**Comment by mykeehu** [comment]
I am using the **LLava Optional Memory Free Advanced** node, and even though the **unload** option is enabled, it is still using more and more VRAM. How can I stop it from consuming VRAM?
