### ISSUE TITLE
 python version 3.9 don't work anymore

### ISSUE THREAD

**Issue by davedaverave** [gokayfem/ComfyUI_VLM_nodes#15]
Since two or three days i can't no longer use this addon.. unfortunatly.. 
it worked before but now ask me to install those packages that are not available in 3.9 ...

Installing collected packages: llama-cpp-python
Successfully installed llama-cpp-python-0.2.26+cu121
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Missing or outdated packages: llama-cpp-agent, mkdocs, mkdocs-material, mkdocstrings[python], docstring-parser
Installing/Updating missing packages...
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10; 0.0.10 Requires-Python >=3.10; 0.0.11 Requires-Python >=3.10; 0.0.12 Requires-Python >=3.10; 0.0.13 Requires-Python >=3.10; 0.0.14 Requires-Python >=3.10; 0.0.15 Requires-Python >=3.10; 0.0.16 Requires-Python >=3.10; 0.0.17 Requires-Python >=3.10; 0.0.2 Requires-Python >=3.10; 0.0.3 Requires-Python >=3.10; 0.0.4 Requires-Python >=3.10; 0.0.5 Requires-Python >=3.10; 0.0.6 Requires-Python >=3.10; 0.0.7 Requires-Python >=3.10; 0.0.8 Requires-Python >=3.10; 0.0.9 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement llama-cpp-agent (from versions: none)
ERROR: No matching distribution found for llama-cpp-agent
Traceback (most recent call last):
  File "/notebooks/ComfyUI/nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 32, in <module>
    check_requirements_installed(llama_cpp_agent_path)
  File "/notebooks/ComfyUI/custom_nodes/ComfyUI_VLM_nodes/__init__.py", line 22, in check_requirements_installed
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', *missing_packages])
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'pip', 'install', 'llama-cpp-agent', 'mkdocs', 'mkdocs-material', 'mkdocstrings[python]', 'docstring-parser']' returned non-zero exit status 1.

**Comment by davedaverave** [comment]
Wow that's unfortunate...thanks anyway! is there a way to use at least joytag? i mean is there a code i could remove or add for that? that at least worked for me three or four days ago ahah

**Comment by gokayfem** [comment]
https://github.com/gokayfem/ComfyUI_VLM_nodes/tree/9b3111cea47825d5d8126f822334253bd769a1f4

this old version doesnt have llama-cpp-agent dependencies. just joytag and llavaloader, llm loader etc..

**Comment by davedaverave** [comment]
God bless you! 🥲
