### ISSUE TITLE
Moondream inference slow even after cuda acceleration installed for llama-cpp-python

### ISSUE THREAD

**Issue by procomp91** [gokayfem/ComfyUI_VLM_nodes#17]
Partly issue, partly solution. The text_model.py for moondream doesn't seem to take advantage of the gpu. Changing device_map to auto accelerated the inference speed on my 3090 from 20s to .5s

`self.model = load_checkpoint_and_dispatch(
            self.model,
            f"{model_path}/text_model.pt",
            device_map="auto",
        )`

**Comment by procomp91** [comment]
also, thanks for the nodes :)

**Comment by gokayfem** [comment]
thanks for the correction, i didnt try moondream node that much, thanks again for excellent feedback 👍
