### ISSUE TITLE
No seed option in LLM and LLAVA

### ISSUE THREAD

**Issue by ShmuelRonen** [gokayfem/ComfyUI_VLM_nodes#18]
Thank you for your important project.

I am trying to synchronize two LLM's with the help of a common seed, but unfortunately the seed option does not exist for some reason. Can you add this option?

![no seed option](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/80190186/c5158704-5512-452a-9cd0-b2dbe13f57f4)

**Comment by gokayfem** [comment]
thanks for the suggestion. i will add it tomorrow in both llava and llama samplers

**Comment by gokayfem** [comment]
its added both in llm sampler and llava sampler advanced
