### ISSUE TITLE
Would it be possible to support the loading of Gemma models?

### ISSUE THREAD

**Issue by rui40000** [gokayfem/ComfyUI_VLM_nodes#20]
https://huggingface.co/lmstudio-ai/gemma-2b-it-GGUF/tree/main
I noticed that the Gemma models are also in Gguf format,
would it be possible to support the loading of Gemma models?
Thanks!  ：）

**Comment by gokayfem** [comment]
i think so once llama-cpp-python uptaded, it will take 1-2 days probably
