### ISSUE TITLE
audioldm2 

### ISSUE THREAD

**Issue by AS1ING** [gokayfem/ComfyUI_VLM_nodes#25]
Hi.
How do I save music to a file after the audioldm2 node?

**Comment by gokayfem** [comment]
its automatically saved in your output folder inside ComfyUI

**Comment by ManOrMonster** [comment]
> its automatically saved in your output folder inside ComfyUI, i will add a saver node soon.

It also ignores the custom outputs path set in extra_model_paths.yaml.
