### ISSUE TITLE
ValueError: not enough values to unpack (expected 1, got 0)

### ISSUE THREAD

**Issue by Datou** [gokayfem/ComfyUI_VLM_nodes#27]
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 26, in <module>
    check_requirements_installed(requirements_path)
  File "C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 11, in check_requirements_installed
    requirements = [pkg_resources.Requirement.parse(line.strip()) for line in f if line.strip()]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 11, in <listcomp>
    requirements = [pkg_resources.Requirement.parse(line.strip()) for line in f if line.strip()]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\.venv\Lib\site-packages\pkg_resources\__init__.py", line 3190, in parse
    (req,) = parse_requirements(s)
    ^^^^^^
ValueError: not enough values to unpack (expected 1, got 0)

Cannot import C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: not enough values to unpack (expected 1, got 0)

win11
python 3.11.7

how to fix this?

**Comment by gokayfem** [comment]
seems like a file path issue, it cannot detect the content in requirements.txt inside ComfyUI_VLM_nodes i think.

i need to add some error handling for this.

```python
import importlib.util
import os
import importlib
import pkg_resources
import sys
import subprocess

def check_requirements_installed(requirements_path):
    # Check if the requirements file exists
    if not os.path.exists(requirements_path):
        print(f"Requirements file does not exist: {requirements_path}")
        return

    try:
        with open(requirements_path, 'r') as f:
            lines = [line.strip() for line in f if line.strip()]
            if not lines:
                print("Requirements file is empty.")
                return

            requirements = [pkg_resources.Requirement.parse(line) for line in lines]
    except ValueError as e:
        print(f"Error parsing requirements file: {e}")
        return
    except Exception as e:
        print(f"An error occurred while reading the requirements file: {e}")
        return

    installed_packages = {pkg.key: pkg for pkg in pkg_resources.working_set}
    missing_packages = []
    for requirement in requirements:
        if requirement.key not in installed_packages or not installed_packages[requirement.key] in requirement:
            missing_packages.append(str(requirement))

    if missing_packages:
        print(f"Missing or outdated packages: {', '.join(missing_packages)}")
        print("Installing/Updating missing packages...")
        subprocess.check_call([sys.executable, '-s', '-m', 'pip', 'install', *missing_packages])
    else:
        print("All packages from requirements.txt are installed and up to date.")
 ``` 
 
 can you change the ```check_requirements_installed``` function with this inside ```__init__.py``` in VLM_nodes

**Comment by Datou** [comment]
> seems like a file path issue, it cannot detect the content in requirements.txt inside ComfyUI_VLM_nodes i think.
> 
> i need to add some error handling for this.
> 
> ```python
> import importlib.util
> import os
> import importlib
> import pkg_resources
> import sys
> import subprocess
> 
> def check_requirements_installed(requirements_path):
>     # Check if the requirements file exists
>     if not os.path.exists(requirements_path):
>         print(f"Requirements file does not exist: {requirements_path}")
>         return
> 
>     try:
>         with open(requirements_path, 'r') as f:
>             lines = [line.strip() for line in f if line.strip()]
>             if not lines:
>                 print("Requirements file is empty.")
>                 return
> 
>             requirements = [pkg_resources.Requirement.parse(line) for line in lines]
>     except ValueError as e:
>         print(f"Error parsing requirements file: {e}")
>         return
>     except Exception as e:
>         print(f"An error occurred while reading the requirements file: {e}")
>         return
> 
>     installed_packages = {pkg.key: pkg for pkg in pkg_resources.working_set}
>     missing_packages = []
>     for requirement in requirements:
>         if requirement.key not in installed_packages or not installed_packages[requirement.key] in requirement:
>             missing_packages.append(str(requirement))
> 
>     if missing_packages:
>         print(f"Missing or outdated packages: {', '.join(missing_packages)}")
>         print("Installing/Updating missing packages...")
>         subprocess.check_call([sys.executable, '-s', '-m', 'pip', 'install', *missing_packages])
>     else:
>         print("All packages from requirements.txt are installed and up to date.")
> ```
> 
> can you change the `check_requirements_installed` function with this inside `__init__.py` in VLM_nodes
> 
> ![image](https://private-user-images.githubusercontent.com/88277926/307868701-39d6b015-0a8e-4850-b9ff-a8ffde0d4f7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NjUyMzUsIm5iZiI6MTcwODk2NDkzNSwicGF0aCI6Ii84ODI3NzkyNi8zMDc4Njg3MDEtMzlkNmIwMTUtMGE4ZS00ODUwLWI5ZmYtYThmZmRlMGQ0ZjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDE2Mjg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxZmJkODAyOTViMGZmOGFlMWQyMmVlZTRjZjZiYzBjMzk4NWEyZGMxOTA5Zjg2MDI2MTdmZTg4MmUyYTUwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vfFL2cpnZvHUYcUkbOvhJeq8b3Ix068BZJlx3C9orVQ)
> 
> this lines up to 24

errror message chaged.

Error parsing requirements file: not enough values to unpack (expected 1, got 0)
llama-cpp installed
All packages from requirements.txt are installed and up to date.
AutoGPTQ installed
Traceback (most recent call last):
  File "C:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\__init__.py", line 69, in <module>
    imported_module = importlib.import_module(f".nodes.{module_name}", __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\internlm.py", line 8, in <module>
    import torch, auto_gptq
  File "C:\ComfyUI\.venv\Lib\site-packages\auto_gptq\__init__.py", line 1, in <module>
    from .modeling import AutoGPTQForCausalLM, BaseQuantizeConfig
  File "C:\ComfyUI\.venv\Lib\site-packages\auto_gptq\modeling\__init__.py", line 1, in <module>
    from ._base import BaseQuantizeConfig
  File "C:\ComfyUI\.venv\Lib\site-packages\auto_gptq\modeling\_base.py", line 33, in <module>
    from ..utils.data_utils import collate_data
  File "C:\ComfyUI\.venv\Lib\site-packages\auto_gptq\utils\__init__.py", line 1, in <module>
    from .perplexity_utils import Perplexity
  File "C:\ComfyUI\.venv\Lib\site-packages\auto_gptq\utils\perplexity_utils.py", line 5, in <module>
    from datasets import load_dataset
ImportError: cannot import name 'load_dataset' from 'datasets' (C:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\datasets\__init__.py)

Cannot import C:\ComfyUI\custom_nodes\ComfyUI_VLM_nodes module for custom nodes: cannot import name 'load_dataset' from 'datasets' (C:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\datasets\__init__.py)

**Comment by gokayfem** [comment]
i think the ComfyUI_OOTDiffusion_CXH nodes has some conflicts with my nodes

**Comment by Datou** [comment]
> i think the ComfyUI_OOTDiffusion_CXH nodes has some conflicts with my nodes

yes. fixed. thank you.
