### ISSUE TITLE
Could you add a node to fully work with chat?

### ISSUE THREAD

**Issue by BenderBlender** [gokayfem/ComfyUI_VLM_nodes#3]
Could you add a node to fully work with chat (or a switch that disables automatic generation of prompt)?
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/116355906/ccb5f2ba-69c5-4580-bbc0-7043d1a4f98f)

something like that?
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/116355906/00dc6505-b56d-4607-9477-9e33522d4c9d)

**Comment by gokayfem** [comment]
i added "SimpleChat Node"

![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/05ef4360-da32-4900-a8c4-75b4523c29b1)

you can ask anything to it
