### ISSUE TITLE
help resolve this issue please

### ISSUE THREAD

**Issue by RYG81** [gokayfem/ComfyUI_VLM_nodes#30]
"D:\000AI\00ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\audioldm2.py", line 1, in <module>     from diffusers import AudioLDM2Pipeline ImportError: cannot import name 'AudioLDM2Pipeline' from 'diffusers' (D:\000AI\00ComfyUI\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by gokayfem** [comment]
the problem is your diffusers version i think.

```
pip install --quiet --upgrade git+https://github.com/huggingface/diffusers.git
```

**Comment by RYG81** [comment]
i install it under custom nodes -vlm package folder?

**Comment by gokayfem** [comment]
no 

```
D:\000AI\00ComfyUI\python_embeded\python.exe pip install --quiet --upgrade git+https://github.com/huggingface/diffusers.git
```
