### ISSUE TITLE
change of model download path?

### ISSUE THREAD

**Issue by RYG81** [gokayfem/ComfyUI_VLM_nodes#32]
Hi,
I don't know if true but download path keep changes for models. some time it downloads in custom node folder and sometime in cache folder under huggingface hub folder, and now we have folder for it in models folder. Any way to fix it to specific folder?

**Comment by gokayfem** [comment]
i made a new update to repo yesterday, now all of the files downloads into models/LLavacheckpoints, this is more convenient.

**Comment by RYG81** [comment]
So how can I move old downloads to this new location and save download data and time?

**Comment by gokayfem** [comment]
you can move them and it will work, even if you dont move them huggingface will find them i think

**Comment by RYG81** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/10570236/e82551a2-2f60-4e4d-b340-a1ba0251bddb)
Just moving this folder data to new folders in model folder

**Comment by gokayfem** [comment]
yes you can move the folder ```files_for_uform_gen2_qwen``` to ```models/LLavacheckpoints```

**Comment by RYG81** [comment]
thanks for the guidance. Hope to have more vision model support added. All the best and keep good work.

**Comment by gokayfem** [comment]
> thanks for the guidance. Hope to have more vision model support added. All the best and keep good work.

which one do you want

**Comment by RYG81** [comment]
Suggestion for vision model - https://huggingface.co/spaces/Vision-CAIR/MiniGPT-v2
also it keeps downloading models, i have created all nodes and downloaded all required models in folder but still evrytime i run it downloads models under user .cache\huggingface\hub folder
PLease fix this as it takes very long and hard to break downloading process

**Comment by RYG81** [comment]
I am getting this error when using kosmos2 and internlm

Error occurred when executing Kosmos2model:

Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated : 9.50 GiB
Requested : 508.10 MiB
Device limit : 8.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
: 17179869184.00 GiB

File "D:\000AI\ComfyUI\ComfyUI\execution.py", line 149, in recursive_execute
obj = class_def()
^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\kosmos2.py", line 55, in __init__
self.predictor = KosmosModelPredictor()
^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\kosmos2.py", line 21, in __init__
self.model = AutoModelForVision2Seq.from_pretrained(self.model_path).to(self.device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 2595, in to
return super().to(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1152, in to
return self._apply(convert)
^^^^^^^^^^^^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
module._apply(fn)
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
module._apply(fn)
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 802, in _apply
module._apply(fn)
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 825, in _apply
param_applied = fn(param)
^^^^^^^^^
File "D:\000AI\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1150, in convert
return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by gokayfem** [comment]
internlm is a heavy model even it's quantized version. also its not downloading, its fetching your old files from this repository from the root.

**Comment by RYG81** [comment]
https://github.com/Sanster/VLM-demos

**Comment by RYG81** [comment]
Models keep downloading, i have used ufromgen2 before and have all models on location, but still it keeps downloading

https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/10570236/c99498e1-b27c-4abc-b4cd-b33c331e044d
