### ISSUE TITLE
Can't download the files about node "audioldm2"

### ISSUE THREAD

**Issue by yingtao-xie** [gokayfem/ComfyUI_VLM_nodes#34]
I downloaded the relevant files manually on hugging face, how should I place them?

![屏幕截图 2024-03-03 233755](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/54252903/d79f4c3d-9a62-43ae-abdd-070baa6e571b)
It doesn't work that way, and shows errors: 

An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

**Comment by gokayfem** [comment]
if you are sure about you download the all of the files. change ```local_files_only=True``` in the ```audiolmd2.py``` inside ```ComfyUI_VLM_nodes/nodes``` folder

**Comment by yingtao-xie** [comment]
> if you are sure about you download the all of the files. change `local_files_only=True` in the `audiolmd2.py` inside `ComfyUI_VLM_nodes/nodes` folder

Yes, I downloaded all files related to audioldm2, but I still can't run this node. The file structure on hugging face is maintained in the folder "files_for_audioldm2". Can u share the structures and content of this folder, plz?

ps, even though I rewrote the option of "local_files_only", it didn't work.

The error:
Cannot find an appropriate cached snapshot folder for the specified revision on the local disk and outgoing traffic has been disabled. To enable repo look-ups and downloads online, pass 'local_files_only=False' as input.

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/f4d8bea7-07f2-4f1b-97de-50ec2ba2b6b0)

this is the structure, as same as you, it is 4.17 gb.

```
class AudioLDM2ModelPredictor:
    
    def __init__(self):
        from diffusers import AudioLDM2Pipeline
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        torch_dtype = torch.float16 if self.device == "cuda" else torch.float32

        # Use snapshot_download to manage the model download/cache
        self.model_path = snapshot_download("cvssp/audioldm2",
                                            local_dir=files_for_audio_model,
                                            force_download=False,  # Set to True to always download
                                            local_files_only=False,  # Download if not available locally
                                            use_auth_token=False,  # Set to True if using a private model
                                            local_dir_use_symlinks="auto",  # Auto-manage symlinks
                                            ignore_patterns=["*.bin", "*.jpg", "*.png"])  # Ignore unrelated files

        self.pipeline = AudioLDM2Pipeline.from_pretrained(self.model_path, 
                                                          torch_dtype=torch_dtype).to(self.device)
        self.generator = torch.Generator(self.device)
 ```
 
 change above code with this
 
 ```
 class AudioLDM2ModelPredictor:
    
    def __init__(self):
        from diffusers import AudioLDM2Pipeline
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        torch_dtype = torch.float16 if self.device == "cuda" else torch.float32

        # Use snapshot_download to manage the model download/cache
        self.model_path = files_for_audio_model

        self.pipeline = AudioLDM2Pipeline.from_pretrained(self.model_path, 
                                                          torch_dtype=torch_dtype).to(self.device)
        self.generator = torch.Generator(self.device)
```
