### ISSUE TITLE
Regarding the prompt generator

### ISSUE THREAD

**Issue by za-wa-n-go** [gokayfem/ComfyUI_VLM_nodes#38]
<img width="702" alt="image" src="https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/118154415/f60901b8-17c1-4d3f-afa1-b7e0b46a6348">

It does not produce the output as I want, excluding unnecessary brackets or "prompt:" like in the sample.

**Comment by gokayfem** [comment]
use jsontotext node to extract the prompt, it will clean the generate word also

**Comment by za-wa-n-go** [comment]
thankyou!
great!!
