### ISSUE TITLE
Feature request: Drop in any model?

### ISSUE THREAD

**Issue by LankyPoet** [gokayfem/ComfyUI_VLM_nodes#4]
Thank you for making this!
Can it be possible to be able to use any local model that is dropped into a directory structure?

For instance I searched for other "vision" models, found this, which I would like to try:
https://huggingface.co/NousResearch/Nous-Hermes-2-Vision-Alpha

Is that possible to allow a user to just add any model? Or does each model need special handling?

**Comment by gokayfem** [comment]
currently not implemented but im working on it. my original plan was adding small models like moondream.

**Comment by LankyPoet** [comment]
Wonderful, thank you so much! I have tried moondream with another node and it is OK. But was looking to try a bunch to figure out which works best. 
thank you again!

**Comment by gokayfem** [comment]
i added LLaVa models from llama-cpp-python

**Comment by LankyPoet** [comment]
Awesome! Thank you, will check it out
