### ISSUE TITLE
ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last):

### ISSUE THREAD

**Issue by wibur0620** [gokayfem/ComfyUI_VLM_nodes#43]
What kind of mistake is this?
[comfyui.txt](https://github.com/gokayfem/ComfyUI_VLM_nodes/files/14547773/comfyui.txt)

**Comment by gokayfem** [comment]
moondream2 has some bugs right now, use other nodes

**Comment by wibur0620** [comment]
Okay, I thought I didn't have enough video memory.

**Comment by gokayfem** [comment]
i down graded the transformers to 4.36.2 this solved the problem.
