### ISSUE TITLE
No module named 'transformers.models.fastspeech2_conformer.configuration_fastspeech2_conformer'

### ISSUE THREAD

**Issue by KumaPlayWithShader** [gokayfem/ComfyUI_VLM_nodes#48]
Error occurred when executing UformGen2QwenNode:

Failed to import transformers.models.fastspeech2_conformer.configuration_fastspeech2_conformer because of the following error (look up to see its traceback):
No module named 'transformers.models.fastspeech2_conformer.configuration_fastspeech2_conformer'

**Comment by gokayfem** [comment]
update transformers library if you want to use this i think

click install pip packages inside ComfyUI Manager

write ```transformers>=4.38.2```

then restart ComfyUI

![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/00e5c070-49eb-4460-bc4a-9a081bf6bf95)

**Comment by KumaPlayWithShader** [comment]
Error occurred when executing Kosmos2model:

Failed to import transformers.models.vipllava.configuration_vipllava because of the following error (look up to see its traceback):
No module named 'transformers.models.vipllava.configuration_vipllava'

**Comment by formulake** [comment]
I just realised the conflict was in the requirements.txt where the older version of transformers was specified, so it was overwriting itself.

**Comment by KumaPlayWithShader** [comment]
Those LLM models  work well with transformer now, thank,  So Great,

(But chat musican seems has different problem.)
