### ISSUE TITLE
[Feature Request]  Support GBNF grammar

### ISSUE THREAD

**Issue by nomadoor** [gokayfem/ComfyUI_VLM_nodes#49]
I learned that llama-cpp has an option to specify a GBNF grammar format.

The ability to specify formats precisely in this way, rather than through prompts, is very appealing, especially since I’m using VLM/LLM for conditional branching and as a tagger.

I would appreciate it if this could be entered as an option for the LLaVA/LLM Sampler.

Thank you.

**Comment by gokayfem** [comment]
We actually have a better way to get structured outputs, i was thinking about this. We have llama-cpp-agents, it uses pydantic to get structured outputs and uses every kind of functionality. This is already installed inside VLM nodes and i use it in some nodes like Suggester and KeywordExtraction nodes. I might add a another node for users to specify what kind of outputs they want. Like this:

Type:List, Description:(furnitures in the picture) etc... 

https://github.com/Maximilian-Winter/llama-cpp-agent

I will think about this i dont know if it will be used widely though.

**Comment by gokayfem** [comment]
Also in the mean time you can change the code inside the suggest.py to get your desired outputs. You only need to change field names and their descriptions.

**Comment by nomadoor** [comment]
![extraction](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/124905471/1ef4b04b-c61b-4b3f-a34f-a60de7df1f58)
I tried the KeywordExtraction node for now, and it outputted as a binary of 1 or 0, just as I expected!
I will also try the literal.

**Comment by nomadoor** [comment]
Yes, that would greatly improve usability and versatility😍

**Comment by gokayfem** [comment]
When you think about this. It can do step by step thinking and can call the llm multiple times.
I can say extract keywords from given description, create different prompts for each keyword. Divide this "1024x1024" canvas into extracted keyword count, assign them coordinates and height and witdh and give me back the coordinate and prompts. With this structured format. We can use this output as a regional prompter for example. That would be great creative use case. I saw similar process to this.

**Comment by nomadoor** [comment]
[RPG-DiffusionMaster](https://github.com/YangLing0818/RPG-DiffusionMaster) is doing exactly that.
No one in ComfyUI has been able to implement it yet, but it’s exciting to think that it could be realized so simply!

**Comment by gokayfem** [comment]
I will try it with using VLM nodes. At least getting coordinates and prompts part. Other parts can be adapted using other custom_nodes.

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/0cb0292b-45cc-4b6d-9a7e-c61c1856bec4)

it doesnt seem that hard.

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/7aa79cf1-27e3-46b3-8d36-ed399f9f4777)

this is the result.

![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/580c8346-a12f-4b06-abdc-47b4f6432531)

currently it creates random areas in canvas and makes prompts for each area

**Comment by nomadoor** [comment]
It’s perfect!
The problem is how to pass this to ComfyUI…
Both ConditioningSetArea and attention-couple and regional prompt require one node for one area, so they can’t be combined well.

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/38a31091-dee3-45ef-9e36-42b819e2cdbd)

https://openart.ai/workflows/nondaa/put-two-person-together-automatically---autoprompting-regional-prompt-ipadapter-controlnet/1chHG0gh6pEy1sZvVE1j

this is my workflow maybe this kind of workflow can do it

**Comment by gokayfem** [comment]
https://github.com/mirabarukaso/ComfyUI_Mira i also discovered this node, we can use his methods i think.

**Comment by gokayfem** [comment]
![ComfyUI_00515_](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/38f6c01d-38e1-4c35-8ecf-0c040d0c7d31)

[workflow-Area_Cimposition_Examples.json](https://github.com/gokayfem/ComfyUI_VLM_nodes/files/14621536/workflow-Area_Cimposition_Examples.json)

also this

**Comment by nomadoor** [comment]
Being able to create a mask by specifying an area is good, but in the end, it’s connected to the regional prompt of the impact pack, so the need for N nodes to set the condition remains unchanged…hmm...
We need something like fizz nodes for area specification.

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/f1a87d1a-24d4-416b-ada7-f866a14b65e2)

i think x,y values are a little bit weird i need to think about their position but otherwise this is pretty okay for me

**Comment by gokayfem** [comment]
i need a reasoning step in the middle how it should divide the canvas with like webui format 1,1,2;1,2,4,6 kind of formatting. that way it would be easy to add this to mira nodes.

**Comment by nomadoor** [comment]
It took me some time to understand this format, it’s not very intuitive…
Personally, I feel a format like CSS grid is simpler and also easier for LLM to understand, but it can’t utilize mira nodes.

**Comment by gokayfem** [comment]
yes, its very confusing, i didnt even understand it for like a 20 minutes. but if it can be automatically done, people wont notice it i think. it can be done internally.

**Comment by nomadoor** [comment]
As you say, as long as we can understand LLM, it’s not a problem that needs to be prioritized.
However, how should we instruct this format…

**Comment by gokayfem** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/38faa583-3fa9-4b8d-ba31-3c2c1755900f)

![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/88277926/56672a68-0a46-4819-b38a-8ec403d026bb)

i made this kind of node is this what you want ?

**Comment by nomadoor** [comment]
Wow! This is exactly what I’ve been looking for! It’s amazing!

**Comment by gokayfem** [comment]
I've added this to repository, you can update the nodes.

**Comment by nomadoor** [comment]
This is very easy to use! Thank you.
Are you planning to support LLaVA?
It would be more versatiley to implement it as an option in the LLM/LLaVA Sampler, rather than creating a new node…

**Comment by gokayfem** [comment]
currently it is not available in llava models, i will try to make it but llama-cpp-agent doesnt support multimodel structured outputs for now.

**Comment by nomadoor** [comment]
I see, that's how it is.
For the time being, it should be fine to pass the output of LLaVA to StructuredOutput.
