### ISSUE TITLE
Links to download models are inaccessible at huggingface

### ISSUE THREAD

**Issue by curreta** [gokayfem/ComfyUI_VLM_nodes#51]
This issue appears to be only the listed models, as at the time of doing this huggingface itself is still up.

https://github.com/gokayfem/ComfyUI_VLM_nodes?tab=readme-ov-file#vlm-nodes

**Comment by curreta** [comment]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/284943/bcc76979-a307-4d90-833b-e3c5f045268d)

The links listed hang, and huggingface never returns the page. (left side image)

**Comment by gokayfem** [comment]
Probably its a temporary issue, it will be fixed soon by huggingface.

**Comment by gokayfem** [comment]
I've opened a topic in huggingface models forum for this issue.

https://discuss.huggingface.co/c/models/13

**Comment by gokayfem** [comment]
now, its okay.
