### ISSUE TITLE
Models keep downloading, i have used ufromgen2 before and have all models on location, but still it keeps downloading

### ISSUE THREAD

**Issue by RYG81** [gokayfem/ComfyUI_VLM_nodes#52]
Models keep downloading, i have used ufromgen2 before and have all models on location, but still it keeps downloading

https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/10570236/c99498e1-b27c-4abc-b4cd-b33c331e044d

_Originally posted by @RYG81 in https://github.com/gokayfem/ComfyUI_VLM_nodes/issues/32#issuecomment-2006707302_

**Comment by gokayfem** [comment]
```python
class UformGen2QwenChat:
    def __init__(self):
        self.model_path = snapshot_download("unum-cloud/uform-gen2-qwen-500m", 
                                            local_dir=files_for_uform_gen2_qwen,
                                            force_download=False,  # Set to True if you always want to download, regardless of local copy
                                            local_files_only=False,  # Set to False to allow downloading if not available locally
                                            local_dir_use_symlinks="auto") # or set to True/False based on your symlink preference
        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.model = AutoModel.from_pretrained(self.model_path, trust_remote_code=True).to(self.device)
        self.processor = AutoProcessor.from_pretrained(self.model_path, trust_remote_code=True)
```
can you change this into this

```python
class UformGen2QwenChat:
    def __init__(self):
        self.model_path = files_for_uform_gen2_qwen
        self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
        self.model = AutoModel.from_pretrained(self.model_path, trust_remote_code=True).to(self.device)
        self.processor = AutoProcessor.from_pretrained(self.model_path, trust_remote_code=True)
```

and try it

**Comment by RYG81** [comment]
Yes I can try this, but will this remain in place on updating node in future?

**Comment by gokayfem** [comment]
no, this is a tricky situation, i need to update this part. if this folders are not empty it should use it like this else it should download. i will look into this today.

**Comment by RYG81** [comment]
Then I think I should not try, as I am not good at coding, and don't want to break the working thing.  I can wait for a day or two.

**Comment by curlysasha** [comment]
> ```python
> class UformGen2QwenChat:
>     def __init__(self):
>         self.model_path = files_for_uform_gen2_qwen
>         self.device = "cuda:0" if torch.cuda.is_available() else "cpu"
>         self.model = AutoModel.from_pretrained(self.model_path, trust_remote_code=True).to(self.device)
>         self.processor = AutoProcessor.from_pretrained(self.model_path, trust_remote_code=True)
> ```

we are waiting for fixing :)
