### ISSUE TITLE
EvoVLM-JP-v1-7B Support

### ISSUE THREAD

**Issue by saftle** [gokayfem/ComfyUI_VLM_nodes#58]
Currently one of the best VLMs is EvoVLM-JP-v1-7B that just released this week. You can grab it here: https://huggingface.co/SakanaAI/EvoVLM-JP-v1-7B. It has code on the huggingface page to get it easily running locally as well.

I'd love to see this somehow working in comfyui, considering it scores even better than LLava 1.6. You can see the scores here: 
<img width="1321" alt="evovlm-results" src="https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/852777/38d203a1-0cbd-41de-afad-fd272534767a">
(Source: https://sakana.ai/evolutionary-model-merge/)

It also works perfectly in English, however sometimes you just need to remind it to only respond in English. Otherwise the VLM is quite accurate at describing images.

Thanks for the consideration!

**Comment by gokayfem** [comment]
we should request gguf version of this. maybe they can provide that. even with these scores without gguf or gptq version, i dont think many people use this. what do you think? i will consider to add this.

**Comment by saftle** [comment]
@gokayfem I believe this one is a GPTQ version: https://huggingface.co/camenduru/EvoVLM-JP-v1-7B-4bit

**Comment by gokayfem** [comment]
i will try to make it work today

**Comment by saftle** [comment]
@gokayfem Thanks for the help, but it looks like it already works with this GGUF version. https://huggingface.co/mmnga/SakanaAI-EvoLLM-JP-v1-7B-gguf/tree/main
