### ISSUE TITLE
Node is not generating new answers each time

### ISSUE THREAD

**Issue by simartem** [gokayfem/ComfyUI_VLM_nodes#62]
Api Prompt Generator has no variable inputs (except the api itself, but it is also a static data), for this reason the node does not generate new answers for the same question in comfyui when the prompt is queued each time (because it would be nice to get different answers for generating various images), answer has already been generated. To get a new answer for same question, what could be done ?

**Comment by gokayfem** [comment]
change temperature a little bit like 0.01
