### ISSUE TITLE
The VRAM usage is too high and cannot be released.

### ISSUE THREAD

**Issue by QL-boy** [gokayfem/ComfyUI_VLM_nodes#67]
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/46901341/b4e5bd36-e02f-420b-b4de-acc129f50c09)
![image](https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/46901341/8c6f66d3-149a-4c07-9c64-3a055c9a4193)

The model will not be unloaded from the VRAM after each generation, and using multiple identical nodes will load the model multiple times, resulting in high VRAM usage.

The screenshot shows the LLM VRAM usage after running the workflow once after a fresh boot and automatically unloading the SD model.

Even using `--disable-smart-memory` doesn't help.

Even if I use a 4090 graphics card, I still can't bear this consumption.

Is there any way to automatically unload the model from the VRAM after each generation? Or is there any other solution that can reduce the model's video memory usage?

**Comment by gokayfem** [comment]
im working on the gpu memory release after generation. i will add this to all of the vlm nodes.
