### ISSUE TITLE
ChatMuscian Error

### ISSUE THREAD

**Issue by BuffMcBigHuge** [gokayfem/ComfyUI_VLM_nodes#69]
```
  File "~\ComfyUI\custom_nodes\ComfyUI_VLM_nodes\nodes\suggest.py", line 428, in chat_musician
    abc_notation = re.findall(abc_pattern, f"{response['choices'][0]['message']['content']}\n")[0]
IndexError: list index out of range
```

Can't seem to get ChatMusician working. It looks like it generates but fails at the end.

<img width="856" alt="Screenshot 2024-04-12 at 2 02 31 PM" src="https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/20268348/0211d49d-b01f-4df7-931f-60db8dc4d22d">

<img width="725" alt="Screenshot 2024-04-12 at 2 03 50 PM" src="https://github.com/gokayfem/ComfyUI_VLM_nodes/assets/20268348/e3385bdb-674d-4c89-97a7-1daa5f5df3ce">

**Comment by gokayfem** [comment]
Yes this model works sometimes but halucinates most of the time. I couldnt make it work %100 everytime. Also authors of the paper confirmes this in their blog. When you get errors you should queue prompt again and again it with the same prompt. 

https://ezmonyi.github.io/ChatMusician/

There is a lot of examples here.
