### ISSUE TITLE
requesting deepseek-vl and qwen-vl nodes

### ISSUE THREAD

**Issue by synryn** [gokayfem/ComfyUI_VLM_nodes#89]
https://huggingface.co/Qwen/Qwen-VL-Chat/tree/main

https://huggingface.co/deepseek-ai/deepseek-vl-7b-chat

I've gotten extremely good results off of these, would be great to have them baseline included as a node in ComfyUI

**Comment by gokayfem** [comment]
im planning to add mantis, llava lama3, llava phi3, idefics 8b, deepseekvl, qwen vl, internlm 4khd, nanollava, paligemma, cogvlm2, comu all together, currently working on it.

**Comment by synryn** [comment]
> im planning to add mantis, llava lama3, llava phi3, idefics 8b, deepseekvl, qwen vl, internlm 4khd, nanollava, paligemma, cogvlm2, comu all together, currently working on it.

Wow, amazing. Thanks for the hard work 🫡

**Comment by gokayfem** [comment]
+ i have 5 vlms that i fine tuned for prompt generation, i will add them also

[https://huggingface.co/gokaygokay](https://huggingface.co/gokaygokay)

**Comment by synryn** [comment]
New phi-3 vision just dropped too, though I haven't tested it yet https://huggingface.co/microsoft/Phi-3-vision-128k-instruct

**Comment by gokayfem** [comment]
yes, im aware of it and tested it, i dont know it was bad luck but it failed my 2 pictures those include text inside it. thanks for the suggestion, benchmarks look extremely good, i dont know if it applies to real world yet.
