### ISSUE TITLE
When huggingface-hub==0.20.3 is forcibly installed, ComfyUI fails to start.

### ISSUE THREAD

**Issue by za-wa-n-go** [gokayfem/ComfyUI_VLM_nodes#91]
Older versions of huggingface-hub prevent ComfyUI from starting due to compatibility issues with other custom nodes.
How can this be resolved? Is there an issue with the latest version?

**Comment by gokayfem** [comment]
okay it should be fixed now

**Comment by za-wa-n-go** [comment]
Thank you for your prompt response!
It seems we should also support the Mac branch.

**Comment by gokayfem** [comment]
sorry, about that fixed it also.

**Comment by za-wa-n-go** [comment]
Thank you for your prompt response!!
