### ISSUE TITLE
Add Bunny support

### ISSUE THREAD

**Issue by tommitytom** [gokayfem/ComfyUI_VLM_nodes#97]
I've been playing with this VLM recently and got some pretty good results. Would be a nice addition to this already impressive node pack :)
Repo: https://github.com/BAAI-DCAI/Bunny
Demo: http://bunny.baai.ac.cn/

**Comment by gokayfem** [comment]
They are coming like every 15 days lol, i dont think i can add all of them. I am trying to add famous ones.
